from sklearn.feature_extraction.text import CountVectorizer

In [161]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm

In [162]:
class Category:
  ELECTROSTATIC = "ELECTROSTATIC"
  THERMODYNAMIC = "THERMODYNAMIC"

train_x = ["charge is conserve","there are two types of charge","zeroth law of thermodynamic", "first law of thermodynamic"]
train_y = [Category.ELECTROSTATIC, Category.ELECTROSTATIC, Category.THERMODYNAMIC, Category.THERMODYNAMIC]

In [163]:
vectorizer = CountVectorizer(binary =True)
vectorizer = CountVectorizer(binary =True, ngram_range=(1,2))
# vectors = vectorizer.fit_transform(train_x)
train_x_vec = vectorizer.fit_transform(train_x)


train_x_vec = train_x_vec.toarray()

print(vectorizer.get_feature_names_out())

print(train_x_vec)

['are' 'are two' 'charge' 'charge is' 'conserve' 'first' 'first law' 'is'
 'is conserve' 'law' 'law of' 'of' 'of charge' 'of thermodynamic' 'there'
 'there are' 'thermodynamic' 'two' 'two types' 'types' 'types of' 'zeroth'
 'zeroth law']
[[0 0 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1]
 [0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0]]


In [164]:
print(vectorizer.get_feature_names_out())

print(train_x_vec[2])

['are' 'are two' 'charge' 'charge is' 'conserve' 'first' 'first law' 'is'
 'is conserve' 'law' 'law of' 'of' 'of charge' 'of thermodynamic' 'there'
 'there are' 'thermodynamic' 'two' 'two types' 'types' 'types of' 'zeroth'
 'zeroth law']
[0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 1 1]


In [165]:

# Using the class which we define already
# class Category:
#   ELECTROSTATIC = "ELECTROSTATIC"
#   NLM = "NLM"

# train_x = ["charge is conserve","there are two types of charge","force is a push or pull", "force is a vector quantity"]
# train_y = [Category.ELECTROSTATIC, Category.ELECTROSTATIC, Category.NLM, Category.NLM]

# Vectorizing the text data
vectorizer = CountVectorizer(binary=True)
train_x_vec = vectorizer.fit_transform(train_x)

# Converting to dense array
train_x_vec = train_x_vec.toarray()

# Creating an SVM classifier
clf_svm = svm.SVC(kernel='linear')

# Attempt to fit the SVM model and catch any potential errors
try:
    # Fit the SVM model
    clf_svm.fit(train_x_vec, train_y)
    fit_error = None
except Exception as e:
    fit_error = e



In [166]:
# Output the shapes of train_x_vec and train_y and any error message
train_x_vec_shape = train_x_vec.shape
train_y_shape = np.array(train_y).shape

train_x_vec_shape, train_y_shape, fit_error if fit_error else "No Error"

((4, 12), (4,), 'No Error')

In [167]:
test_x = vectorizer.transform(['opposite charge attracts']).toarray()  # Convert to dense array
prediction = clf_svm.predict(test_x)
print(prediction)


['ELECTROSTATIC']


In [168]:
test_x = vectorizer.transform(['charge can cause electrostatic force']).toarray()
clf_svm.predict(test_x)

array(['ELECTROSTATIC'], dtype='<U13')

## As we can see above our model doesnt give us what we are looking for.
# 1. We need to use other aprroach such as .. Word Vectors
# What is does basically , it capture the semantic meaning of a word in a vector.